name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 18.231.251.174
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/gabriel-prova-final
            git pull origin main
            cd backend
            sudo docker build -t courses-api .
            sudo docker rm -f courses-api || true
            sudo docker run -d \
              --name courses-api \
              --restart unless-stopped \
              -p 3000:3000 \
              --env-file /home/ubuntu/gabriel-prova-final/backend/.env \
              courses-api
