name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    if: |
      contains(toJson(github.event.commits), 'backend/')

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 18.231.251.174
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/gabriel-prova-final
            git pull origin main
            cd backend
            sudo docker build -t courses-api .
            sudo docker rm -f courses-api || true
            sudo docker run -d \
              --name courses-api \
              --restart unless-stopped \
              -p 3000:3000 \
              --env-file /home/ubuntu/gabriel-prova-final/backend/.env \
              courses-api

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 18.231.251.174
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/gabriel-prova-final
            git pull origin main
            cd frontend
            sudo docker build \
              --build-arg VITE_AUTH0_DOMAIN=dev-wu34pp41bwi2w0q8.us.auth0.com \
              --build-arg VITE_AUTH0_CLIENT_ID=KzEMbGj653BIOnJ5pnY1etdJbglXPa3z \
              --build-arg VITE_AUTH0_AUDIENCE=https://courses-api \
              --build-arg VITE_API_URL=http://18.231.251.174 \
              -t courses-frontend .
            sudo docker rm -f courses-frontend caddy || true
            sudo docker run -d \
              --name courses-frontend \
              --restart unless-stopped \
              --network host \
              courses-frontend
